namespace :markus do
  
  desc "Create a single Administrator with username a"
  task(:admin => :environment) do
    puts "Creating Administrator with username 'a'..."
    a = Admin.new({:user_name => 'a', :first_name => 'admin', :last_name => 'admin'})
    a.save
  end
  
  desc "Create a setup for usability testing. You have to run db:populate before this task!"
  task(:usability_test_setup => :environment) do
    puts "Creating a setup for usability testing"
    # modify settings for A1 (solo assignment)
    a1 = Assignment.find_by_name("A1")
    req_file1 = AssignmentFile.new
    req_file1.filename = "conditionals.py"
    req_file1.assignment_id = a1.id
    req_file2 = AssignmentFile.new
    req_file2.filename = "loops.py"
    req_file2.assignment_id = a1.id
    a1.due_date = 1.week.from_now # due date is a week from now
    a1.message += "\nNote: You are working alone for this assignment."
    a1.group_min = 1
    a1.group_max = 1
    a1.save
    req_file1.save
    req_file2.save
    
    # modify settings for A2
    a2 = Assignment.find_by_name("A2")
    a2.due_date = 2.week.from_now # due date is 2 weeks from now
    a2.message += "\nNote: You are working in groups for this assignment. Please form groups on your own."
    # students can form groups
    a2.group_min = 3
    a2.group_max = 5
    a2.instructor_form_groups = false
    req_file1 = AssignmentFile.new
    req_file1.filename = "Animal.java"
    req_file1.assignment = a2
    req_file2 = AssignmentFile.new
    req_file2.filename = "Cat.java"
    req_file2.assignment = a2
    req_file3 = AssignmentFile.new
    req_file3.filename = "Dog.java"
    req_file3.assignment = a2
    rule = NoLateSubmissionRule.new
    a2.save
    req_file1.save
    req_file2.save
    req_file3.save
    
    # Create a third assignment, for which the instructor has formed groups
    groups_csv_string = "Saturn,ignored_repo,c9magnar,c6scriab,g9merika\n
                         Mars,irgnored_repo,c9puccin,c7stanfo,g5dindyv\n
                         Neptune,ignored_repo,c7dallap,c7guarni,c7kimear"
    a3 = Assignment.create(:name => "A3", :description => "Shell Scripting",
    :message => "Learn how to use functions, parameter passing and proper return codes.\nNote: You have been assigned to a group by the instructor.",
    :group_min => 1, :group_max => 1, :student_form_groups => false,
    :group_name_autogenerated => true, :group_name_displayed => true,
    :repository_folder => "A3", :due_date => 3.week.from_now, :instructor_form_groups => true)
    req_file1 = AssignmentFile.new
    req_file1.filename = "gcd.sh"
    req_file1.assignment = a2
    a3.submission_rule = rule
    a3.save
    # create groupings/groups
    groups_csv_string.split("\n").each do |row|
      a3.add_csv_group(row.split(","))
    end
    req_file1.save
  end
end
