require 'faker'

FactoryGirl.define do
  factory :assignment do
    short_identifier Faker::Name.first_name
    description Faker::Lorem.sentence
    message Faker::Lorem.sentence
    group_min 1
    group_max 1
    student_form_groups false
    group_name_autogenerated true
    group_name_displayed false
    repository_folder Faker::Name.first_name
    due_date 1.minute.from_now
    marking_scheme_type Assignment::MARKING_SCHEME_TYPE[:rubric]
    allow_web_submits true
    display_grader_names_to_students false
    submission_rule NoLateSubmissionRule.new
    assignment_stat AssignmentStat.new
  end
end
