extends: ["stylelint-config-sass-guidelines"]
rules:
  scss/at-extend-no-missing-placeholder: null
  scss/no-global-function-names: null
  max-nesting-depth: 4
  selector-class-pattern: null
  selector-max-compound-selectors: 6
  selector-max-id: 2
  selector-no-qualifying-type: null
