describe ApplicationHelper do
  describe '#inline_svg_data_uris' do
    # Build an <img> tag whose src is a base64 SVG data URI.
    #   quote: wrap the src value in " or '
    #   attrs: extra attributes inserted right after `<img`
    def svg_img(svg, quote: '"', attrs: '')
      encoded = Base64.strict_encode64(svg)
      %(<img#{attrs} src=#{quote}data:image/svg+xml;base64,#{encoded}#{quote}>)
    end

    let(:plain_svg) do
      '<svg xmlns="http://www.w3.org/2000/svg"><rect width="10" height="10"/></svg>'
    end

    # --- happy path -------------------------------------------------------

    it 'replaces an SVG data-URI <img> with the inlined SVG markup' do
      result = helper.inline_svg_data_uris(svg_img(plain_svg))
      expect(result).to eq(plain_svg)
    end

    it 'preserves surrounding HTML around the replaced image' do
      html = %(<div class="wrap">#{svg_img(plain_svg)}</div>)
      result = helper.inline_svg_data_uris(html)
      expect(result).to eq(%(<div class="wrap">#{plain_svg}</div>))
    end

    it 'replaces multiple SVG data-URI images in one document' do
      svg_a = '<svg id="a"><circle r="1"/></svg>'
      svg_b = '<svg id="b"><rect width="2" height="2"/></svg>'
      html = "#{svg_img(svg_a)} and #{svg_img(svg_b)}"
      result = helper.inline_svg_data_uris(html)
      expect(result).to eq("#{svg_a} and #{svg_b}")
    end

    # --- prolog / doctype / comment stripping -----------------------------

    it 'strips an <?xml?> prolog before the <svg> root' do
      svg = %(<?xml version="1.0" encoding="UTF-8"?>\n#{plain_svg})
      result = helper.inline_svg_data_uris(svg_img(svg))
      expect(result).to eq(plain_svg)
      expect(result).not_to include('<?xml')
    end

    it 'strips a DOCTYPE and leading comments before the <svg> root' do
      svg = %(<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "x.dtd">\n<!-- generated by something -->\n#{plain_svg})
      result = helper.inline_svg_data_uris(svg_img(svg))
      expect(result).to eq(plain_svg)
      expect(result).not_to include('DOCTYPE')
      expect(result).not_to include('<!--')
    end

    # --- attribute / quoting variations -----------------------------------

    it 'handles single-quoted src attributes' do
      result = helper.inline_svg_data_uris(svg_img(plain_svg, quote: "'"))
      expect(result).to eq(plain_svg)
    end

    it 'matches when other attributes precede src' do
      img = svg_img(plain_svg, attrs: %( class="logo" width="32"))
      expect(helper.inline_svg_data_uris(img)).to eq(plain_svg)
    end

    # --- things it should NOT touch ---------------------------------------

    it 'leaves non-SVG data URIs untouched' do
      png = %(<img src="data:image/png;base64,#{Base64.strict_encode64('not-an-svg')}">)
      expect(helper.inline_svg_data_uris(png)).to eq(png)
    end

    it 'leaves ordinary image URLs untouched' do
      img = %(<img src="/assets/logo.svg" alt="logo">)
      expect(helper.inline_svg_data_uris(img)).to eq(img)
    end

    it 'leaves text without matching <img> tags unchanged' do
      html = '<p>No images here</p>'
      expect(helper.inline_svg_data_uris(html)).to eq(html)
    end

    # --- nil / empty handling ---------------------------------------------

    it 'returns an empty string for nil' do
      expect(helper.inline_svg_data_uris(nil)).to eq('')
    end

    it 'returns an empty string for an empty string' do
      expect(helper.inline_svg_data_uris('')).to eq('')
    end

    # --- characterization tests (document current behavior) ---------------
    # These pin down behavior that is arguably surprising, so a future change
    # that "fixes" it will fail loudly and force a deliberate decision.

    it 'inlines decoded content unchanged when there is no <svg> root (no validation)' do
      garbage = 'just some text, no svg root'
      img = %(<img src="data:image/svg+xml;base64,#{Base64.strict_encode64(garbage)}">)
      # The prolog-stripping sub is a no-op without an <svg>, so raw bytes pass through.
      expect(helper.inline_svg_data_uris(img)).to eq(garbage)
    end

    it 'returns a plain (non-html_safe) String' do
      result = helper.inline_svg_data_uris(svg_img(plain_svg))
      expect(result).to be_a(String)
      expect(result).not_to be_html_safe
    end

    it 'inlines an SVG containing a <script> element as-is (no sanitization)' do
      # Highlights the XSS surface: once inlined into the DOM the script can run,
      # unlike the original <img src=data:...> form. Change this test the day you
      # add sanitization.
      malicious = '<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>'
      result = helper.inline_svg_data_uris(svg_img(malicious))
      expect(result).to include('<script>alert(1)</script>')
    end
  end
end
