# frozen_string_literal: true

require 'tempfile'

module Jupyter
  class SubmissionsController < ApplicationController
    # Local prototype only.
    # For production, replace these skips with proper MarkUs/JupyterHub authorization.
    skip_before_action :verify_authenticity_token, only: [:submit], raise: false
    skip_verify_authorized only: :submit

    def submit
      payload = params

      jupyter_info = payload['jupyter'] || {}
      jupyter_path = payload['notebook_path']

      destination_path = sanitize_destination_path(
        payload['destination_path'].presence ||
          payload['notebook_name'].presence ||
          File.basename(jupyter_path.to_s)
      )

      user = find_user_from_jupyter_token!(jupyter_info)
      course = find_course_from_payload!(payload)

      student = course.roles.find_by(user_id: user.id)

      if student.nil?
        raise ActiveRecord::RecordNotFound,
              t(
                'jupyter.submissions.errors.student_role_not_found',
                user_name: user.user_name.inspect,
                course_id: course.id
              )
      end

      assignment = find_assignment_from_payload!(payload, course)

      grouping = if student.has_accepted_grouping_for?(assignment.id)
                   student.accepted_grouping_for(assignment.id)
                 elsif assignment.group_max == 1
                   student.create_group_for_working_alone_student(assignment.id)
                   student.accepted_grouping_for(assignment.id)
                 else
                   student.create_autogenerated_name_group(assignment)
                 end

      jupyter_file = JupyterNotebookFetcher.new(
        origin: jupyter_info['origin'],
        base_url: jupyter_info['base_url'],
        token: jupyter_info['token'],
        notebook_path: jupyter_path
      ).fetch

      submitted_file = tempfile_from_jupyter_file!(
        jupyter_file: jupyter_file,
        destination_path: destination_path
      )

      Rails.logger.info(
        "[Jupyter::SubmissionsController] Submitting #{destination_path} " \
        "for user=#{user.user_name}, " \
        "course_id=#{course.id}, " \
        "assignment_id=#{assignment.id}, grouping_id=#{grouping.id}"
      )

      submit_jupyter_file!(
        grouping: grouping,
        assignment: assignment,
        path: destination_path,
        file: submitted_file
      )

      render json: {
        status: 'success',
        message: t('jupyter.submissions.submit.success'),
        submitted_file: destination_path,
        markus_target: {
          course_id: course.id,
          assignment_id: assignment.id,
          assignment: assignment.short_identifier,
          repository_folder: assignment.repository_folder,
          grouping_id: grouping.id,
          group_id: grouping.group_id,
          student_role_id: student.id,
          markus_user_name: user.user_name
        },
        fetched_file: {
          name: jupyter_file[:name],
          path: jupyter_file[:path],
          type: jupyter_file[:type],
          format: jupyter_file[:format]
        }
      }, status: :ok
    rescue JupyterIdentityFetcher::IdentityError => e
      render json: {
        status: 'error',
        message: e.message,
        error_class: e.class.name
      }, status: :unauthorized
    rescue JupyterNotebookFetcher::FetchError => e
      render json: {
        status: 'error',
        message: e.message,
        error_class: e.class.name
      }, status: :bad_gateway
    rescue ActiveRecord::RecordNotFound, ArgumentError => e
      render json: {
        status: 'error',
        message: e.message,
        error_class: e.class.name
      }, status: :not_found
    rescue StandardError => e
      Rails.logger.error("[Jupyter::SubmissionsController] #{e.class}: #{e.message}")
      Rails.logger.error(e.backtrace.join("\n")) if e.backtrace

      render json: {
        status: 'error',
        message: e.message,
        error_class: e.class.name
      }, status: :internal_server_error
    ensure
      submitted_file&.close
      submitted_file&.unlink
    end

    private

    def find_user_from_jupyter_token!(jupyter_info)
      username = resolve_jupyter_username!(jupyter_info)

      Rails.logger.info(
        "[Jupyter::SubmissionsController] Jupyter token resolved to username=#{username}"
      )

      user = User.find_by(user_name: username)

      if user.nil?
        raise ActiveRecord::RecordNotFound,
              t(
                'jupyter.submissions.errors.user_not_found',
                user_name: username.inspect
              )
      end

      user
    end

    def find_course_from_payload!(payload)
      if payload['course_id'].present?
        return Course.find(payload['course_id'])
      end

      course_name = payload['course'].to_s.strip

      if course_name.blank?
        raise ActiveRecord::RecordNotFound,
              t('jupyter.submissions.errors.missing_course')
      end

      course = Course.find_by(name: course_name)

      if course.nil?
        raise ActiveRecord::RecordNotFound,
              t(
                'jupyter.submissions.errors.course_not_found',
                course: course_name.inspect
              )
      end

      course
    end

    def find_assignment_from_payload!(payload, course)
      assignment = if payload['assignment_id'].present?
                     course.assignments.find_by(id: payload['assignment_id'])
                   elsif payload['assignment'].present?
                     course.assignments.find_by(
                       short_identifier: payload['assignment'].to_s.strip
                     )
                   else
                     raise ActiveRecord::RecordNotFound,
                           t('jupyter.submissions.errors.missing_assignment')
                   end

      return assignment if assignment.present?

      assignment_value = payload['assignment_id'].presence || payload['assignment'].presence

      raise ActiveRecord::RecordNotFound,
            t(
              'jupyter.submissions.errors.assignment_not_found',
              assignment: assignment_value.inspect,
              course_id: course.id
            )
    end

    def resolve_jupyter_username!(jupyter_info)
      # Local development fallback only.
      # This is useful when testing with standalone JupyterLab, where the token
      # authenticates the server but does not identify a real JupyterHub user.
      if Rails.env.development? && ENV['JUPYTER_DEV_USERNAME'].present?
        return ENV.fetch('JUPYTER_DEV_USERNAME', nil)
      end

      JupyterIdentityFetcher.new(
        origin: jupyter_info['origin'],
        base_url: jupyter_info['base_url'],
        token: jupyter_info['token']
      ).username
    end

    def tempfile_from_jupyter_file!(jupyter_file:, destination_path:)
      submitted_file = Tempfile.new(
        ['jupyter-submission', File.extname(destination_path)]
      )

      submitted_file.binmode
      submitted_file.write(jupyter_file[:content])
      submitted_file.rewind
      submitted_file
    end

    def submit_jupyter_file!(grouping:, assignment:, path:, file:)
      sanitized_path = sanitize_destination_path(path)

      if assignment.only_required_files
        required_file = assignment.assignment_files.find_by(filename: sanitized_path)

        if required_file.nil?
          raise ArgumentError,
                t(
                  'jupyter.submissions.errors.required_file_missing',
                  filename: sanitized_path.inspect
                )
        end
      end

      # TODO:
      # Replace this block with the exact MarkUs repository write call.
      #
      # The reviewer asked not to reuse SubmissionsHelper#upload_file because it does
      # too many API-specific things. This method should only:
      #   1. validate the submitted path,
      #   2. check required files when assignment.only_required_files is true,
      #   3. add the raw tempfile content to the grouping repository.
      #
      # Check the existing SubmissionsHelper#upload_file implementation and copy only
      # the lower-level repository write part.
      grouping.access_repo do |repo|
        repo.add_file(
          sanitized_path,
          file.read,
          "Submit #{sanitized_path} from Jupyter"
        )
      end
    end

    def sanitize_destination_path(path)
      filename = File.basename(path.to_s.strip)

      if filename.blank?
        raise ArgumentError,
              t('jupyter.submissions.errors.destination_filename_missing')
      end

      filename
    end
  end
end
