# frozen_string_literal: true

require 'tempfile'

module Jupyter
  class JupyterSubmissionsController < ApplicationController
    include RepositoryHelper

    # Local prototype only.
    #
    # The Jupyter endpoint resolves the submitting user separately, so it
    # should not require an existing MarkUs browser session.
    skip_before_action :verify_authenticity_token, only: [:submit], raise: false
    skip_before_action :authenticate, only: [:submit]
    skip_before_action :check_record, only: [:submit]
    skip_before_action :check_course_switch, only: [:submit]

    skip_verify_authorized only: :submit

    def submit
      payload = params

      Rails.logger.info(
        "[Jupyter::JupyterSubmissionsController] Incoming payload: " \
        "#{payload.to_unsafe_h.except('controller', 'action').inspect}"
      )

      jupyter_info = payload['jupyter'] || {}
      jupyter_path = payload['notebook_path']

      destination_path = sanitize_destination_path(
        payload['destination_path'].presence ||
          payload['notebook_name'].presence ||
          File.basename(jupyter_path.to_s)
      )

      user = find_user_from_jupyter_token!(jupyter_info)
      course = find_course_from_payload!(payload)

      student = course.roles.find_by(user_id: user.id)

      if student.nil?
        raise ActiveRecord::RecordNotFound,
              "MarkUs user #{user.user_name.inspect} does not have a role " \
              "in course id=#{course.id}, name=#{course.name.inspect}."
      end

      assignment = find_assignment_from_payload!(payload, course)

      grouping =
        if student.has_accepted_grouping_for?(assignment.id)
          student.accepted_grouping_for(assignment.id)
        elsif assignment.group_max == 1
          student.create_group_for_working_alone_student(assignment.id)
          student.accepted_grouping_for(assignment.id)
        else
          student.create_autogenerated_name_group(assignment)
        end

      jupyter_file = JupyterNotebookFetcher.new(
        origin: jupyter_info['origin'],
        base_url: jupyter_info['base_url'],
        token: jupyter_info['token'],
        notebook_path: jupyter_path
      ).fetch

      submitted_file = tempfile_from_jupyter_file!(
        jupyter_file: jupyter_file,
        destination_path: destination_path
      )

      Rails.logger.info(
        "[Jupyter::JupyterSubmissionsController] " \
        "Submitting #{destination_path} " \
        "for user=#{user.user_name}, " \
        "course_id=#{course.id}, " \
        "assignment_id=#{assignment.id}, " \
        "grouping_id=#{grouping.id}"
      )

      submit_jupyter_file!(
        grouping: grouping,
        assignment: assignment,
        student: student,
        path: destination_path,
        file: submitted_file
      )

      render json: {
        status: 'success',
        message: 'Notebook submitted successfully.',
        submitted_file: destination_path,
        markus_target: {
          course_id: course.id,
          course: course.name,
          assignment_id: assignment.id,
          assignment: assignment.short_identifier,
          repository_folder: assignment.repository_folder,
          grouping_id: grouping.id,
          group_id: grouping.group_id,
          student_role_id: student.id,
          markus_user_name: user.user_name
        },
        fetched_file: {
          name: jupyter_file[:name],
          path: jupyter_file[:path],
          type: jupyter_file[:type],
          format: jupyter_file[:format]
        }
      }, status: :ok

    rescue JupyterIdentityFetcher::IdentityError => e
      render json: {
        status: 'error',
        message: e.message,
        error_class: e.class.name
      }, status: :unauthorized

    rescue JupyterNotebookFetcher::FetchError => e
      render json: {
        status: 'error',
        message: e.message,
        error_class: e.class.name
      }, status: :bad_gateway

    rescue ActiveRecord::RecordNotFound, ArgumentError => e
      render json: {
        status: 'error',
        message: e.message,
        error_class: e.class.name
      }, status: :not_found

    rescue StandardError => e
      Rails.logger.error(
        "[Jupyter::JupyterSubmissionsController] #{e.class}: #{e.message}"
      )

      Rails.logger.error(e.backtrace.join("\n")) if e.backtrace

      render json: {
        status: 'error',
        message: e.message,
        error_class: e.class.name
      }, status: :internal_server_error

    ensure
      submitted_file&.close
      submitted_file&.unlink
    end

    private

    def find_user_from_jupyter_token!(jupyter_info)
      username = resolve_jupyter_username!(jupyter_info)

      Rails.logger.info(
        "[Jupyter::JupyterSubmissionsController] " \
        "Jupyter token resolved to username=#{username.inspect}"
      )

      user = User.find_by(user_name: username)

      if user.nil?
        raise ActiveRecord::RecordNotFound,
              "No MarkUs user exists with user_name=#{username.inspect}."
      end

      user
    end

    def find_course_from_payload!(payload)
      if payload['course_id'].present?
        course_id = payload['course_id'].to_i

        Rails.logger.info(
          "[Jupyter::JupyterSubmissionsController] " \
          "Looking up course by id=#{course_id}"
        )

        return Course.find(course_id)
      end

      course_name = payload['course'].to_s.strip

      if course_name.blank?
        raise ActiveRecord::RecordNotFound,
              'Submission payload must contain course_id or course.'
      end

      Rails.logger.info(
        "[Jupyter::JupyterSubmissionsController] " \
        "Looking up course by name=#{course_name.inspect}"
      )

      course = Course.find_by(name: course_name)

      if course.nil?
        raise ActiveRecord::RecordNotFound,
              "No course exists with name=#{course_name.inspect}."
      end

      course
    end

    def find_assignment_from_payload!(payload, course)
      if payload['assignment_id'].present?
        assignment_id = payload['assignment_id'].to_i

        Rails.logger.info(
          "[Jupyter::JupyterSubmissionsController] " \
          "Looking up assignment id=#{assignment_id} " \
          "inside course id=#{course.id}"
        )

        assignment = course.assignments.find_by(id: assignment_id)

        if assignment.nil?
          available = course.assignments
                            .order(:id)
                            .pluck(:id, :short_identifier)

          raise ActiveRecord::RecordNotFound,
                "Assignment id=#{assignment_id} was not found in " \
                "course id=#{course.id}. " \
                "Available assignments=#{available.inspect}"
        end

        return assignment
      end

      if payload['assignment'].present?
        short_identifier = payload['assignment'].to_s.strip

        Rails.logger.info(
          "[Jupyter::JupyterSubmissionsController] " \
          "Looking up assignment short_identifier=#{short_identifier.inspect} " \
          "inside course id=#{course.id}"
        )

        assignment = course.assignments.find_by(
          short_identifier: short_identifier
        )

        if assignment.nil?
          available = course.assignments
                            .order(:id)
                            .pluck(:id, :short_identifier)

          raise ActiveRecord::RecordNotFound,
                "Assignment #{short_identifier.inspect} was not found in " \
                "course id=#{course.id}. " \
                "Available assignments=#{available.inspect}"
        end

        return assignment
      end

      raise ActiveRecord::RecordNotFound,
            'Submission payload must contain assignment_id or assignment.'
    end

    def resolve_jupyter_username!(jupyter_info)
      # Development-only mapping.
      #
      # A standalone Jupyter token proves access to Jupyter but does not
      # necessarily identify a MarkUs username. For local testing, explicitly
      # map the Jupyter submission to JUPYTER_DEV_USERNAME.
      if Rails.env.development? && ENV['JUPYTER_DEV_USERNAME'].present?
        return ENV.fetch('JUPYTER_DEV_USERNAME')
      end

      JupyterIdentityFetcher.new(
        origin: jupyter_info['origin'],
        base_url: jupyter_info['base_url'],
        token: jupyter_info['token']
      ).username
    end

    def tempfile_from_jupyter_file!(jupyter_file:, destination_path:)
      submitted_file = Tempfile.new(
        ['jupyter-submission', File.extname(destination_path)]
      )

      submitted_file.binmode
      submitted_file.write(jupyter_file[:content])
      submitted_file.rewind

      submitted_file
    end

    def submit_jupyter_file!(grouping:, assignment:, student:, path:, file:)
      sanitized_path = sanitize_destination_path(path)

      required_files =
        if assignment.only_required_files
          assignment.assignment_files.pluck(:filename)
        end

      uploaded_file = ActionDispatch::Http::UploadedFile.new(
        tempfile: file,
        filename: sanitized_path,
        type: 'application/x-ipynb+json'
      )

      file.rewind

      success, messages = grouping.access_repo do |repo|
        add_file(
          uploaded_file,
          student,
          repo,
          path: assignment.repository_folder,
          required_files: required_files
        )
      end

      return if success

      formatted_messages =
        Array(messages)
          .map(&:to_s)
          .reject(&:blank?)
          .join(', ')

      raise StandardError,
            "MarkUs repository submission failed: #{formatted_messages}"
    end

    def sanitize_destination_path(path)
      filename = File.basename(path.to_s.strip)

      if filename.blank?
        raise ArgumentError,
              'Could not determine a destination filename for the submission.'
      end

      filename
    end
  end
end