import {config, dom, library} from "@fortawesome/fontawesome-svg-core";
import {
  faAdd,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faChalkboardUser,
  faChartColumn,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlus,
  faClose,
  faComments,
  faCompress,
  faDice,
  faDownload,
  faEnvelopeCircleCheck,
  faExpand,
  faFile,
  faFileImage,
  faFileImport,
  faFilePdf,
  faFilter,
  faFolder,
  faFolderOpen,
  faFolderPlus,
  faGear,
  faGripVertical,
  faInfo,
  faLink,
  faList,
  faMinus,
  faPen,
  faPeopleGroup,
  faPrint,
  faQuestion,
  faRefresh,
  faRocket,
  faSignOut,
  faSlash,
  faSquareCheck,
  faTable,
  faTrash,
  faUpload,
  faUserGroup,
  faUserMinus,
  faUserPlus,
  faWarning,
} from "@fortawesome/free-solid-svg-icons";

import {faGithub} from "@fortawesome/free-brands-svg-icons";

import {faSquare} from "@fortawesome/free-regular-svg-icons";

config.autoAddCss = false;

library.add(
  faAdd,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faChalkboardUser,
  faChartColumn,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlus,
  faClose,
  faComments,
  faCompress,
  faDice,
  faDownload,
  faEnvelopeCircleCheck,
  faExpand,
  faFile,
  faFileImage,
  faFileImport,
  faFilePdf,
  faFilter,
  faFolder,
  faFolderOpen,
  faFolderPlus,
  faGear,
  faGithub,
  faGripVertical,
  faInfo,
  faLink,
  faList,
  faMinus,
  faPen,
  faPeopleGroup,
  faPrint,
  faQuestion,
  faRefresh,
  faRocket,
  faSignOut,
  faSlash,
  faSquare,
  faSquareCheck,
  faTable,
  faTrash,
  faUpload,
  faUserGroup,
  faUserMinus,
  faUserPlus,
  faWarning
);

dom.watch();
