development:
  adapter: redis
  url: <%= Settings.redis.url %>
  channel_prefix: markus_development
test:
  adapter: test
production:
  adapter: redis
  url: <%= Settings.redis.url %>
  channel_prefix: markus_production
