development:
  secret_key_base: <%= MarkusConfigurator.markus_config_session_cookie_secret %>

test:
  secret_key_base: <%= MarkusConfigurator.markus_config_session_cookie_secret %>

production:
  secret_key_base: <%= MarkusConfigurator.markus_config_session_cookie_secret %>
