# Assignments
rule = NoLateSubmissionRule.new
a = Assignment.create(:short_identifier => "A1", :description => "Conditionals and Loops",
:message => "Learn to use conditional statements, and loops.",
:group_min => 1, :group_max => 1, :student_form_groups => false,
:group_name_autogenerated => true, :group_name_displayed => false,
:repository_folder => "A1", :due_date => 1.minute.from_now)
a.submission_rule = rule
a.save

rule = NoLateSubmissionRule.new
a = Assignment.create(:short_identifier => "A2", :description => "Cats and Dogs",
:message => "Basic exercise in Object Oriented Programming.  Implement Animal, Cat, and Dog, as described in class.", :group_min => 2, :group_max => 3, :student_form_groups => true, :group_name_autogenerated => true, :group_name_displayed => false,
:repository_folder => "A2", :due_date => 1.month.from_now)
a.submission_rule = rule
a.save
