ORACLE_DATABASE = 'ate_oracle'
TEST_DATABASE = 'ate_tests'
USER = 'ate_test'
PASSWORD = 'YOUR_TEST_PASSWORD'
PATH_TO_SCHEMA = '/path/to/schema'
SCHEMA_FILE = 'schema.ddl'
DATA_FILES = ['data1.sql', 'data2.sql']
SCHEMA_NAME = 'ate'
OUTPUT_FILE = 'output.txt'
