rails:
  cache_classes: false
  eager_load: false
  consider_all_requests_local: true
  hosts:
    - host.docker.internal
    - docker.for.mac.localhost
  log_level: debug
  active_support:
    deprecation: stderr
  active_record:
    verbose_query_logs: true
  action_mailer:
    perform_deliveries: true
  action_controller:
    default_url_options:
      host: 'host.docker.internal'
      port: '3000'

puma:
  worker_timeout: 100000000

i18n:
  available_locales:
    - en
  default_locale: en

validate_user_not_allowed_message: 'That is your correct University of Foo user name and password, but you have not been added to this particular MarkUs database.  Please contact your instructor or check your course web page.'
incorrect_login_message: 'Login incorrect. You can check your Foo U user name or reset your password at https://www.foo.example.edu/passwords.'

validate_file: <%= "#{::Rails.root}/config/dummy_validate.sh" %>
remote_auth_login_url: https://www.example.com

logging:
  log_file: log/info_development.log
  error_file: log/error_development.log

autotest:
  max_batch_size: 10

lti:
  course_filter_file: <%= "#{::Rails.root}/config/dummy_lti_config.rb" %>
  domains: <%= %w[host.docker.internal] %>
  token_endpoint: "http://host.docker.internal:3100/login/oauth2/token"
  unpermitted_new_course_message: 'You are not permitted to create a new MarkUs course for %{course_name}. Please contact your system administrator.'
  sync_schedule: "0 3 * * *"
