rails:
  cache_classes: false
  eager_load: false
  consider_all_requests_local: true
  hosts:
    - host.docker.internal
  log_level: debug
  active_support:
    deprecation: stderr
  cache_store: redis_cache_store
  active_record:
    verbose_query_logs: true
  action_mailer:
    perform_deliveries: true

i18n:
  available_locales:
    - en
    - fr
    - es
    - pt
  default_locale: en

validate_user_not_allowed_message: 'That is your correct University of Foo user name and password, but you have not been added to this particular MarkUs database.  Please contact your instructor or check your course web page.'
incorrect_login_message: 'Login incorrect. You can check your Foo U user name or reset your password at https://www.foo.example.edu/passwords.'

repository:
  storage: <%= "#{::Rails.root.to_s}/data/dev" %>/repos

logging:
  log_file: log/info_development.log
  error_file: log/error_development.log

autotest:
  client_dir: <%= "#{::Rails.root.to_s}/data/dev" %>/autotest
  max_batch_size: 10

scanned_exams:
  path: <%= "#{::Rails.root.to_s}/data/dev" %>/exam_templates

starter_file:
  storage: <%= "#{::Rails.root.to_s}/data/dev" %>/starter_files
